FROM python:3.9-slim

RUN mkdir /home/anonym /home/anonym/data /home/anonym/sensitive_identification

COPY api.py pipeline.py anonymize.py meta.py ingesters.py min_req.txt /home/anonym/

COPY models /home/anonym/models
COPY .git /home/anonym/.git

COPY sensitive_identification /home/anonym/sensitive_identification/

COPY data /home/anonym/data

WORKDIR /home/anonym

RUN apt-get update && apt-get install -y git git-lfs unzip

RUN git lfs install && git lfs checkout && git lfs fetch && git lfs pull
RUN unzip models/model_ca_core_lg_iris_05_31.zip -d ./models && rm models/model_ca_core_lg_iris_05_31.zip


RUN python -m pip install -r min_req.txt streamlit spacy_streamlit


ENTRYPOINT ["streamlit", "run", "api.py", "--server.address=0.0.0.0"]